### ISSUE TITLE
Mapping Cleveland's Emergency Snow Ban streets

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/general#13]
While walking to work today, I remembered that I had started making a map of Cleveland's streets that are subject to Cleveland's emergency snow ban (which goes to in effect when there's 2+ inches of snow on the ground) in the winter. 

I started drawing all of the streets in geojson.io and then uploaded it to: https://gist.github.com/skorasaurus/4da6ec96066ba685f45e

Before this map, All that had previously existed were a list of streets; but that doesn't help people if they are going to a new place or even want to know where in their neighborhood, where they could park their car. (NOTE: This list does NOT cover all streets that have an emergency snow ban.... I think this list only covers the streets that do NOT have signs stating they are subject to an emergency snow ban). 

This could be finished by our brigade. 

images of these lists of streets are at: 
https://pbs.twimg.com/media/B9C5jUGIYAAomjE.jpg
https://pbs.twimg.com/media/B92BTyfIEAArXGd.jpg:large
https://clecityhall.files.wordpress.com/2014/11/emer-snow-ban-procedures-streets-11-19-14.pdf (looks like the latest list -- checked on Jan 6, 2016 ado)

sources:
https://twitter.com/joecimperman/status/566751307328147456
https://twitter.com/joecimperman/status/563153972777979904/photo/1

STEPS TO FINISH: 
1. go to https://gist.githubusercontent.com/skorasaurus/4da6ec96066ba685f45e/raw/d93bf90f54dae6cd7d69ba71df176266f01ff86d/map.geojson 
copy and paste all of its content; save the file as snowroutes.geojson
2. go to http://geojson.io ; open the snowroutes.geojson 
3. with your collaborators, check the printed papers and find out which ones have already been mapped (aka: drawn) onto the map. If you need help figuring out where a street is, ask your fellow collaborators or anyone else in attendance. 

4. Done? 

5. Bonus Points; if we have time. Make a custom map of these routes in our cartodb account.

This would be an awesome, practical project for our brigade's participants to learn web mapping concepts and tools (like geojson.io) as well as using github and github pages; 

https://github.com/jwalgran/phl-snow-emergency-routes

**Comment by anastasiado** [comment]
Took the PDF and dumped it into this: 
https://docs.google.com/spreadsheets/d/1b-UPAnFGqALVIIkbLudyd3q_ksR8uQCiunjIcuyaekY/edit?usp=sharing

Everyone should be able to edit and mark when things are done.

**Comment by skorasaurus** [comment]
things to check out: 

East 71st was designated from Grant to st. clair, which is noncontiguous; there's a small strip of east 71st just south of grand ave ;)

**Comment by anastasiado** [comment]
Here's what I did so far. https://gist.github.com/anonymous/941747e5d24c13bdd5bf

**Comment by skorasaurus** [comment]
http://bl.ocks.org/anonymous/raw/bd8380a2aa07da66c456/ - ROB winn's

**Comment by anastasiado** [comment]
Updated: https://gist.github.com/anonymous/7d49c893c824b772d55f

**Comment by RingoKam** [comment]
https://gist.github.com/4915b270596e1a8b4c47

**Comment by kleeson** [comment]
http://bl.ocks.org/d/8a08efe35ab013096a1a

**Comment by kleeson** [comment]
Mostly duplicates (and Lorain): http://bl.ocks.org/d/72d6022a594a7279fa31

**Comment by skorasaurus** [comment]
now at: https://github.com/opencleveland/snowban
