### ISSUE TITLE
update our information on CFA's brigade-info

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/general#15]
the meetup url needs to be changed [in this data set](https://github.com/codeforamerica/brigade-information) that code for america uses. 

a bite sized task for someone familiar with github or wishes to learn github.

**Comment by Freytes** [comment]
Has this task been completed?

**Comment by skorasaurus** [comment]
hey @Freytes - thanks for your interest; this appears to have been fixed; sorry, I forgot to close it!
