### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/general#6]
are we keeping with the existing logo?

**Comment by skorasaurus** [comment]
we're not, decided at last week's meeting; join logo_brainstorm slack channel if you're interested

**Comment by cwang912** [comment]
what are we qualifying as the current logo? the cleveland civic hacking one?

**Comment by skorasaurus** [comment]
@cwang912 yup.

**Comment by skorasaurus** [comment]
done by Ben Bubnick! 

(although should we make it publicly accessible somewhere? right now it's saved on slack..
